"use client"

import type { NextPage } from "next";
import Head from "next/head";
import "./globals.css"
import { LazyImage } from "@/components/LazyImage";
import { MouseEventHandler, useState } from "react";

const randomNumber = (max: number):number => Math.floor(Math.random()*max);
const generateId = ():string =>Math.random().toString(36).substring(2,9);

type ImageType  = {
  id: string,
  url: string
}

const Home: NextPage = () => {

  const source: () => string = () => `https:\/\/randomfox.ca\/images\/${randomNumber(123)}.jpg`
  const [images, setImages] = useState<Array<ImageType>>([]);
  
  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
    event.preventDefault();

    const newImageItem: ImageType = {
      id: generateId(), url: source()
    }

    setImages([
      ...images,
      newImageItem
    ])
  }

  return (
    <div>
      <Head>
        <title>Platzi</title>
        <meta name="description" content="Generated by Platzi"/>
        <link rel="stylesheet" href="/favicon.ico" />
      </Head>
      <h1>Hola Platzi</h1>
      <button onClick={addNewFox}>Add new fox</button>
      {
        images.map((image, index) => (
          <div key={index} className='p-4'>
            <LazyImage
              src={image.url}
              width={320}
              height='auto'
              className='rounded bg-gray-300'
              onClick={() => console.log("Hey")}
              onLazyLoad={(img) => {
                console.log(`Image ${index} loaded, node: `, img);
              }}
            />
          </div>
        ))
      }
    </div>
  )
}

export default Home;